import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Data from "./assets/main_data.json";
import IndexPageTemplate from "./indexPageTemplate";
import { useState } from "react";
import AuthPage from "./auth/authPage";
import { Flex } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { locale, locales, asPath } = useRouter() || {};

  const [currentAuthState, setCurrentAuthState] = useState("");

  return (
    <Flex align="center" justify="center">
      <Head>
        <title>Alpha-Omega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentAuthState === "authenticated" ? (
        <div>
          {Data.main_data
            .filter((p) => p.locale === locale)
            .map((mainsets, i) => {
              return <IndexPageTemplate key={i} mainsets={mainsets} />;
            })}
        </div>
      ) : (
        <Flex align="center" justify="center">
          <AuthPage />
        </Flex>
      )}
    </Flex>
  );
};

export default Home;
