import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Data from "./assets/main_data.json";
import IndexPageTemplate from "./indexPageTemplate";
import { useEffect, useState } from "react";
import AuthPage from "./auth/authPage";
import { Button, Flex, Modal, ModalBody, ModalCloseButton, ModalContent, ModalFooter, ModalHeader, ModalOverlay, useDisclosure } from "@chakra-ui/react";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../../firebaseConfig";

const Home: NextPage = () => {
  const { locale, locales, asPath } = useRouter() || {};

  const { isOpen, onOpen, onClose } = useDisclosure()

  useEffect(() => {
    onOpen()
  }, [])

  return (
    <Flex align="center" justify="center">
      <Head>
        <title>Alpha-Omega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {Data.main_data
          .filter((p) => p.locale === locale)
          .map((mainsets, i) => {
            return <IndexPageTemplate key={i} mainsets={mainsets} />;
          })}
      </div>
      <Modal variant={"purple"} isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent bg="#CCD2FC">
          <ModalHeader>Instructions for the student</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            Welcome to AlphaOmega, a site dedicated to the study of Christian scruptures. 
            Our goal is to supply our students with sufficient textual and lexical metterial 
            to study the greek language through the Christian texts.<br/> 
            <br/>
            For that purpose we supply 
            the student with the whole texts of the Old and New Testament along with additional
            translations. The student can also navigate easily from one chapter to the other.
            Each word is seperately treated as a lemma, meaning that extensive lexical search via 
            tools like Perseus and LSJ is allowed with a single click.<br/>
            <br/>
            Last but not least, the user can search for a particular word within the text using our 
            search tool on the Navbar.<br/>
            <br/>
            To access our content, all that is needed is to make a free subsciption to make 
            our community grow larger and larger. 
          </ModalBody>
        </ModalContent>
      </Modal>
    </Flex>
  );
};

export default Home;
