import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Evangel.io
        </h1>

        <p className={styles.description}>
          A site dedicated to the study of Christian scriptures
        </p>

        <div className={styles.grid}>
          <Link href={'/gosp'}><a className={styles.card}>
            <h2>Old Testament &rarr;</h2>
            <p>From Genesis to the Maccabees</p>
          </a></Link>

          <Link  href={'/'}><a className={styles.card}>
            <h2>New Testament &rarr;</h2>
            <p>From the Gospels to the Apocalypse</p>
          </a></Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/icxc.png" alt="ICXC Logo" width={25} height={25} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
