import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import Data from "./assets/main_data.json";
import Main_tem from "./components/pageTemplates/mainPageTemplate";

const Home: NextPage = () => {
  const { locale, locales, asPath } = useRouter() || {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Alpha-Omega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {Data.main_data
          .filter((p) => p.locale === locale)
          .map((mainsets, i) => {
            return <Main_tem key={i} mainsets={mainsets} />;
          })}
      </div>
    </div>
  );
};

export default Home;
